[profile.default]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@HerodotusDev/solidity-mmr=lib/solidity-mmr",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]
optimize = true
optimizer_runs = 200
via_ir = true


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
