[profile.default]
remappings = [
    "@optimism/libraries=src/libraries/external/optimism",
    "@openzeppelin=lib/openzeppelin-contracts",
    "libraries=src/libraries",
    "interfaces=src/interfaces",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
