[profile.default]
remappings = [
    "@openzeppelin=solidity/lib/openzeppelin-contracts",
    "@solidity-mmr=solidity/lib/solidity-mmr/src",
    # "libraries=src/libraries",
    # "interfaces=src/interfaces",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]
optimize = true
optimizer_runs = 200
via_ir = true
