[profile.default]
remappings = [
    "@optimism/libraries=src/libraries/external/optimism",
    "@openzeppelin=lib/openzeppelin-contracts",
    "@solidity-mmr=lib/solidity-mmr/src",
    "libraries=src/libraries",
    "interfaces=src/interfaces",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]
optimize = true
optimizer_runs = 200
via_ir = true


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
