[profile.default]
remappings = [
    "@optimism/libraries=src/libraries/external/optimism",
    "@openzeppelin=lib/openzeppelin-contracts",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
