[profile.default]
remappings = [
    "@openzeppelin=solidity/lib/openzeppelin-contracts",
    "@HerodotusDev/solidity-mmr=solidity/lib/solidity-mmr",
]
src = "solidity/src"
out = "solidity/out"
libs = ["lib", "libraries"]
optimize = true
optimizer_runs = 200
via_ir = true
