[profile.default]
remappings = [
    "@optimism/libraries=src/libraries/external/optimism",
    "@openzeppelin=lib/openzeppelin-contracts",
    "libraries=src/libraries",
    "interfaces=src/interfaces",
]
src = "src"
out = "out"
libs = ["lib", "libraries"]
