name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
      - uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run bun install
        run: |
          bun install

      - name: Init .env
        env:
          CONFIG_SECRET: ${{ secrets.ENV_CONFIG }}
        run: |
          printf "%s\n" "$CONFIG_SECRET" > .env

      - name: Run Prettier Check
        run: |
          bun prettier:check

      - name: Run Forge build
        run: |
          bun compile
